<?php
namespace app\index\controller;
use think\Controller;
use think\Session;
class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // 继承父类中的初始化操作TODO: Change the autogenerated stub
        define('USER_ID', Session::has('user_id') ? Session::get('user_id'):null);
    }

    //判断用户是否登录
    protected function isLogin(){
        if (is_null(USER_ID)){
            $this->error('用户未登录，无权访问',url('user/login'));
        }
    }

    //防止用户重复登录  user/login
    protected function alreadyLogin(){
        if(USER_ID){
            $this->error('用户已登录',url('index/index'));
        }
    }
}
